### ISSUE TITLE
Android Capture Image Bug

### ISSUE THREAD

**Issue by malikdoksoz** [ricnaaru/adv_camera#1]
`E/error   (30525): lalalalalala=> java.lang.RuntimeException: setParameters failed
I/flutter (30525): camera
W/System.err(30525): java.lang.RuntimeException: setParameters failed
W/System.err(30525): 	at android.hardware.Camera.native_setParameters(Native Method)
W/System.err(30525): 	at android.hardware.Camera.setParameters(Camera.java:2102)
W/System.err(30525): 	at com.ric.adv_camera.AdvCamera.refreshCameraPreview(AdvCamera.java:536)
W/System.err(30525): 	at com.ric.adv_camera.AdvCamera.refreshCamera(AdvCamera.java:526)
W/System.err(30525): 	at com.ric.adv_camera.AdvCamera.access$500(AdvCamera.java:45)
W/System.err(30525): 	at com.ric.adv_camera.AdvCamera$3.onPictureTaken(AdvCamera.java:181)
W/System.err(30525): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1191)
W/System.err(30525): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(30525): 	at android.os.Looper.loop(Looper.java:193)
W/System.err(30525): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err(30525): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(30525): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(30525): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (30525): /data/user/0/com.example.denememalik/app_flutter/adv_camera_20191021_222246.jpg
I/flutter (30525): camera
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): Failed to handle method call
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): java.lang.RuntimeException: takePicture failed
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at android.hardware.Camera.native_takePicture(Native Method)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at android.hardware.Camera.takePicture(Camera.java:1551)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at android.hardware.Camera.takePicture(Camera.java:1493)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at com.ric.adv_camera.AdvCamera.captureImage(AdvCamera.java:193)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at com.ric.adv_camera.AdvCamera.onMethodCall(AdvCamera.java:250)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/adv_camera/0(30525): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (30525): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, takePicture failed, null)
E/flutter (30525): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter (30525): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:316
E/flutter (30525): <asynchronous suspension>
E/flutter (30525): #2      AdvCameraController.captureImage 
package:adv_camera/controller.dart:111
E/flutter (30525): <asynchronous suspension>
E/flutter (30525): #3      _MyAppState.build.<anonymous closure> 
package:denememalik/main.dart:185
E/flutter (30525): #4      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:654
E/flutter (30525): #5      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:729
E/flutter (30525): #6      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter (30525): #7      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:365
E/flutter (30525): #8      TapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:275
E/flutter (30525): #9      PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:455
E/flutter (30525): #10     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:75
E/flutter (30525): #11     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:102
E/flutter (30525): #12     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:218
E/flutter (30525): #13     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (30525): #14     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (30525): #15     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (30525): #16     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (30525): #17     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter (30525): #18     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (30525): #19     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (30525): #20     _invoke1  (dart:ui/hooks.dart:263:10)
E/flutter (30525): #21     _dispatchPointerDataPacket  (dart:ui/hooks.dart:172:5)
E/flutter (30525):
`

**I get this error after I take a photo. Camera freezes and can't take pictures again.**

Android sdk 28 - emulator
flutter 1.9.1.hotfix.5

**Comment by ricnaaru** [comment]
please note this

> For Android's permission, you have to configure it yourself (using Dexter, etc.). This plugin is made to support my other plugin adv_image_picker, so this permission is handled in adv_image_picker

On Android, you have to request permission manually, you can use dexter or another permission requestor plugin on Java. or you can see my code at [adv_image_picker](https://pub.dev/packages/adv_image_picker#-readme-tab-)

or you can manually set camera permission on Android setting
