### ISSUE TITLE
Get image to process

### ISSUE THREAD

**Issue by xellDart** [ricnaaru/adv_camera#13]
On official camera plugin, I can get all frames by
 await _controller.startImageStream((CameraImage image)
 and process image like this 
 FirebaseVisionImage.fromBytes(
        _concatenatePlanes(image.planes),
        _buildMetaData(image, _rotationIntToImageRotation(imageRotation)),
      )

How I can do this with adv_camera?

**Comment by ricnaaru** [comment]
im not planning to do this any sooner, because i dont really need this, probably you can fork this and try to create it yourself. giving that the official Flutter Camera has done it, i think it will be quite easy to move their piece of code here :)
