### ISSUE TITLE
Error opening Android camera

### ISSUE THREAD

**Issue by danielbrito1987** [ricnaaru/adv_camera#16]
When trying to call AdvCamera the following error is returning me:

E/flutter (20137): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference, null)

I already uninstalled and installed the plugin again and the error continues

**Comment by ricnaaru** [comment]
when did the error occur? while opening the camera, or while trying to take picture?

**Comment by danielbrito1987** [comment]
> when did the error occur? while opening the camera, or while trying to take picture?

while opening the camera

**Comment by ricnaaru** [comment]
please try the latest version
