### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by mcsugaman** [ricnaaru/adv_camera#20]
Hi,

is it possible to force camera focus on camera preview?
Now we have to tap screen for focus.
Thanks.

**Comment by shachneff** [comment]
> Hi,
> 
> is it possible to force camera focus on camera preview?
> Now we have to tap screen for focus.
> Thanks.

+1

**Comment by ricnaaru** [comment]
what do you mean by force camera focus? so initially the camera focus is locked at center?

**Comment by shachneff** [comment]
> what do you mean by force camera focus? so initially the camera focus is locked at center?

if you don’t tap with your finger in the live-preview screen, the photo will be cloudy (not in focus)

**Comment by mcsugaman** [comment]
> > what do you mean by force camera focus? so initially the camera focus is locked at center?
> 
> if you don’t tap with your finger in the live-preview screen, the photo will be cloudy (not in focus)

+1

**Comment by Eswarrajpurohit** [comment]
hey i have used stack to overlay something over this widget ,so my question is that ,is there any way to add custom focus point,it would be very kind of you helping me out here

**Comment by ricnaaru** [comment]
this topic is related with #42, please refer to that thread from now on, i will close this one, thanks!
