### ISSUE TITLE
How to stop the camera feed?

### ISSUE THREAD

**Issue by intellitour** [ricnaaru/adv_camera#22]
How do I stop the camera after capturing an image?

**Comment by ricnaaru** [comment]
You can simply render another widget instead of AdvCamera, i believe.. if freeze the camera preview is what you mean, i havent create such method yet

**Comment by intellitour** [comment]
Even when you change screen (eg. navigate to another), camera feed is still going on. It must have a way to stop the camera feed.

**Comment by intellitour** [comment]
This might have some relation with https://github.com/ricnaaru/adv_camera/issues/11

**Comment by ricnaaru** [comment]
okay, let me try to fix this error within this week, thanks!

**Comment by intellitour** [comment]
Thanks!

**Comment by ricnaaru** [comment]
please try the latest version (1.2.0) and if the problem still persists, please kindly reopen this thread. Thanks!
