### ISSUE TITLE
iOS Bug

### ISSUE THREAD

**Issue by malikdoksoz** [ricnaaru/adv_camera#3]
Camera preview not showing and when i clicked torch and change to front camera app is crash.

**Comment by ricnaaru** [comment]
alrighty I'll look into it

can you give me more detail, what ios version did you use?
did you run my example code?

**Comment by malikdoksoz** [comment]
Yes, ur example code. iOS 13.1

**Comment by ricnaaru** [comment]
For now, if you're running it from emulator, it will crash and i haven't trace it yet, but it's actually running smoothly on real device.

**Comment by malikdoksoz** [comment]
You can't open the camera in the iOS simulator of course I tried on the real device

**Comment by ricnaaru** [comment]
Not much clue that I've been given, I tried to run on iPhone 7 plus and it ran smoothly with no problem

can you give me the exact detail of steps that cause this error, or can you record it and send the video to me?
