### ISSUE TITLE
No Camera preview

### ISSUE THREAD

**Issue by dhanuvanth** [ricnaaru/adv_camera#30]
no error in the code but it is not showing any preview. I tried with both android emulated and also real device. but its showing only the progress bar. I used the latest version (adv_camera: ^1.1.1+1). android version - 7,8,9
![Capture](https://user-images.githubusercontent.com/43810498/85927232-5e17b680-b8c2-11ea-99dd-4b399fcc0127.PNG)
![Capture2](https://user-images.githubusercontent.com/43810498/85927241-67088800-b8c2-11ea-920b-7dbdba4541da.PNG)

please help...

**Comment by chadathanainta** [comment]
Add permission in Android  and run on real mobile

**Comment by Abhishek01039** [comment]
can you please let us know which permission we need to give and where? @chadathanainta  @ricnaaru

**Comment by chadathanainta** [comment]
@Abhishek01039

` <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.front" />
    <uses-feature android:name="android.hardware.camera2" android:required="false" />
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>
    <uses-feature android:name="android.hardware.camera.flash" android:required="false" />`

**Comment by Abhishek01039** [comment]
ok thanks @chadathanainta
