### ISSUE TITLE
Calling controller.setFlashType does not activate flash

### ISSUE THREAD

**Issue by SunFoxx** [ricnaaru/adv_camera#56]
I'd been trying to implement some custom controls for a camera view and tried calling `controller.setFlashType` with both `FlashType.on` and `FlashType.torch` values, but it seems like it isn't working. `controller.captureImage()` does not trigger any flash whatsoever. I've tested it on multiple android devices, yet no luck getting it to work.

**Comment by ricnaaru** [comment]
which version are you using?

**Comment by SunFoxx** [comment]
> which version are you using?

2.0.0+1-nullsafety

**Comment by ricnaaru** [comment]
please check the latest version..
